import { TrafficIncident, CityPreset } from './types';

export const CITY_PRESETS: CityPreset[] = [
  { name: 'San Francisco, CA', lat: 37.7749, lng: -122.4194, zoom: 13 },
  { name: 'New York, NY', lat: 40.7128, lng: -74.0060, zoom: 13 },
  { name: 'Chicago, IL', lat: 41.8781, lng: -87.6298, zoom: 13 },
  { name: 'Austin, TX', lat: 30.2672, lng: -97.7431, zoom: 13 },
  { name: 'London, UK', lat: 51.5074, lng: -0.1278, zoom: 13 }
];

export const INITIAL_INCIDENTS: TrafficIncident[] = [
  {
    id: 'inc-1',
    type: 'accident',
    title: 'Multi-Vehicle Collision on I-80 West',
    description: '3 vehicles involved in middle lanes near Bay Bridge approach. First responders on scene, heavy bottleneck forming.',
    locationName: 'I-80 W near Fremont St Exit',
    lat: 37.7892,
    lng: -122.3942,
    severity: 'critical',
    reportedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    reportedBy: 'HighwayPatrolBot & 14 drivers',
    upvotes: 28,
    verified: true,
    laneBlocked: 'Left and Center 2 lanes blocked',
    estimatedClearance: '~45 mins',
    tags: ['Ambulance On Scene', 'Heavy Tow Required']
  },
  {
    id: 'inc-2',
    type: 'road_closure',
    title: 'Emergency Water Main Break & Full Closure',
    description: 'Street flooded and pavement buckling between 4th and 5th St. Both directions fully closed to through traffic.',
    locationName: 'Mission St between 4th & 5th St',
    lat: 37.7834,
    lng: -122.4045,
    severity: 'critical',
    reportedAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    reportedBy: 'CityWorks_Dispatch',
    upvotes: 42,
    verified: true,
    laneBlocked: 'All lanes closed both ways',
    estimatedClearance: 'Until 6:00 PM',
    tags: ['Full Road Closure', 'Detour Active']
  },
  {
    id: 'inc-3',
    type: 'accident',
    title: 'Fender Bender blocking Right Lane',
    description: 'Minor two-car collision at intersection. Waiting for police report, causing tailback towards Market.',
    locationName: 'Van Ness Ave & Geary Blvd',
    lat: 37.7858,
    lng: -122.4215,
    severity: 'minor',
    reportedAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    reportedBy: 'Commuter_Alex',
    upvotes: 9,
    verified: false,
    laneBlocked: 'Right turn lane restricted',
    estimatedClearance: '~15 mins',
    tags: ['Minor Delay', 'Passable']
  },
  {
    id: 'inc-4',
    type: 'construction',
    title: 'Nightly Resurfacing & Heavy Machinery',
    description: 'Caltrans ongoing asphalt milling. Cones deployed with rolling slowdowns.',
    locationName: 'Hwy 101 South near Cesar Chavez St',
    lat: 37.7512,
    lng: -122.4068,
    severity: 'moderate',
    reportedAt: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    reportedBy: 'Caltrans_AutoAlert',
    upvotes: 19,
    verified: true,
    laneBlocked: 'Right two lanes',
    estimatedClearance: 'Open at 5:00 AM',
    tags: ['Scheduled Work', 'Speed Limit 35 MPH']
  },
  {
    id: 'inc-5',
    type: 'hazard',
    title: 'Debris / Fallen Cargo in Express Lane',
    description: 'Large wooden ladder and pallet fragments fallen on roadway. Drivers swerving rapidly.',
    locationName: 'I-280 Northbound near Monterey Blvd',
    lat: 37.7314,
    lng: -122.4412,
    severity: 'moderate',
    reportedAt: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
    reportedBy: 'Driver_SamanthaR',
    upvotes: 17,
    verified: true,
    laneBlocked: 'Fast lane impacted',
    estimatedClearance: 'Road Crew En Route',
    tags: ['Debris Alert', 'Hazardous']
  },
  {
    id: 'inc-6',
    type: 'road_closure',
    title: 'Embarcadero Weekend Farmers Plaza Closure',
    description: 'Civic pedestrian zone event. Regular vehicle detours posted via Battery and Sansome.',
    locationName: 'The Embarcadero at Ferry Plaza',
    lat: 37.7955,
    lng: -122.3937,
    severity: 'minor',
    reportedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    reportedBy: 'SFMTA Official',
    upvotes: 35,
    verified: true,
    laneBlocked: 'Northbound access restricted',
    estimatedClearance: 'Reopening at 4:00 PM',
    tags: ['Event Detour', 'Pedestrian Traffic']
  }
];
